[package]
name = "nbitmask"
version = "1.0.0"
edition = "2021"
authors = ["Bastien Scheurer <bastien.scheurer.pro@gmail.com"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
